# Generated by Django 2.0.3 on 2018-03-09 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_no', models.CharField(max_length=10)),
                ('receipt_date', models.CharField(max_length=15)),
                ('receipt_amount', models.CharField(max_length=6)),
                ('receipt_amount_str', models.CharField(max_length=255)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice')),
            ],
            options={
                'db_table': 'inv_receipt',
                'ordering': ('receipt_id',),
            },
        ),
    ]
