# Generated by Django 2.0.3 on 2018-03-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.IntegerField()),
                ('contract_no', models.CharField(max_length=10)),
                ('contract_date', models.DateField()),
                ('client_id', models.IntegerField()),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=30)),
                ('invoice', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'inv_data_vw',
                'managed': False,
            },
        ),
    ]
