# Generated by Django 2.0.3 on 2018-03-09 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=30)),
                ('client_email', models.CharField(max_length=100)),
                ('client_address', models.CharField(max_length=500)),
                ('client_orc', models.CharField(blank=True, max_length=50, null=True)),
                ('client_cui', models.CharField(blank=True, max_length=50, null=True)),
                ('client_bank', models.CharField(blank=True, max_length=50, null=True)),
                ('client_account', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'inv_client',
                'ordering': ('client_name',),
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_no', models.CharField(max_length=10)),
                ('contract_date', models.DateField(verbose_name='From')),
                ('status', models.CharField(choices=[('disabled', 'Disabled'), ('enabled', 'Enabled')], default='enabled', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Client')),
            ],
            options={
                'db_table': 'inv_contract',
                'ordering': ('contract_date',),
            },
        ),
        migrations.CreateModel(
            name='ContractService',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'inv_service',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(max_length=10)),
                ('invoice_date', models.CharField(max_length=15)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Contract')),
            ],
            options={
                'db_table': 'inv_invoice',
                'ordering': ('invoice_date',),
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('invoice_line_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.ContractService')),
            ],
            options={
                'db_table': 'inv_invoice_line',
                'ordering': ('invoice_line_id',),
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=100)),
                ('provider_phone', models.CharField(max_length=30)),
                ('provider_email', models.CharField(max_length=100)),
                ('provider_address', models.CharField(max_length=500)),
                ('provider_orc', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_cui', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_bank', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_account', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'inv_provider',
                'ordering': ('provider_name',),
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Provider'),
        ),
    ]
